#!/usr/bin/env bash

ARGS_NUMBER=$#

OUTPUT=$(zenity --file-selection --directory --title="Choose target directory")

if [ "$?" -eq 1 ]; then
  # zenity --error --text="Cancelled"
  exit 1
fi

TARGETDIR=$(awk -F, '{print $1}' <<<"$OUTPUT")

for ((i = 1; i <= "$ARGS_NUMBER"; i++)); do
  echo "# ${1##*/}"
  cp -p -r "$(readlink -f "${1}")" "$TARGETDIR/"
  echo "$(((i * 100) / "$ARGS_NUMBER"))"
  sleep 0.1
  shift 1
done | zenity --progress --title="Copy files to $TARGETDIR" --percentage=0 --auto-close

if [ "$?" -eq 1 ]; then
  zenity --error --text="Cancelled!"
  exit 1
fi
