#!/usr/bin/env bash

cmd=$(zenity --entry --width=250 --title "Cmd" --text "Enter the command to apply to selected file(s)")

# Check if tags is an empty string using -z
if [[ -z "$cmd" ]]; then
  zenity --info --text="No command entered"
  exit 1
fi

if [ "$CAJA_SCRIPT_SELECTED_FILE_PATHS" = "$IFS" ]; then
  zenity --info --text='No files selected, exiting' --title='Cmd'
else
  IFS_BAK=$IFS
  IFS="
    "
  for file in $CAJA_SCRIPT_SELECTED_FILE_PATHS; do
    $cmd "$(readlink -f "$file")"
  done
  IFS=$IFS_BAK
fi
