#!/usr/bin/env bash

# Created by oss-lvr (https://github.com/oss-lvr)
# View checksum of any file from Caja

if [ "$CAJA_SCRIPT_SELECTED_FILE_PATHS" = "$IFS" ]; then
  zenity --info --text='No files selected, exiting' --title='Checksum'
else
  #Get what the user wants
  ans=$(zenity --list --text "Select the method" --title='Checksum' --radiolist --column "Pick" --column "options" TRUE "md5sum" FALSE "sha1sum" FALSE "sha256sum" FALSE "sha512sum")
  if [ "$ans" = "$IFS" ]; then
    zenity --info --text='Nothing to do, exiting' --title='Checksum'
  else
    # By default, space is delimiter, changing it temporarily to new line
    IFS_BAK=$IFS
    IFS="
    "

    declare res

    # Iterateover file names
    for file in $CAJA_SCRIPT_SELECTED_FILE_PATHS; do
      res+="$($ans "$(readlink -f "$file")")\n"
    done

    # Reset delimiter to space
    IFS=$IFS_BAK

    # Show calculated checksums to the user
    zenity --info --title="$ans  /path/to/file" --width=700 --text="$res"
  fi
fi
